from setuptools import setup

setup(
    name="flask-base",
    version="1.0.0",
    packages=["flask_base"],
    url="https://github.com/wobeng/flask-base",
    license="",
    author="wobeng",
    author_email="wobeng@yblew.com",
    description="flask base app",
    install_requires=[
        "Flask",
        "werkzeug",
        "marshmallow",
        "simplejson",
        "flasgger",
        "apispec",
        "apispec-webframeworks",
        "PyYAML",
        "flask-cors",
        "bcrypt",
        "python-dateutil",
        "phonenumbers",
        "requests",
        "validators",
        "more_itertools",
        "jsonschema",
        "pytz",
        "netaddr",
        "py-tools @ git+https://git@github.com/wobeng/py-tools.git@master#egg=py-tools-1.0.0",
    ],
)
